# Generated by Django 2.0.3 on 2018-03-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.CharField(max_length=400)),
                ('pizza_id', models.IntegerField()),
                ('pizza_size', models.PositiveSmallIntegerField(choices=[(30, 'AVERAGE'), (50, 'BIG')])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
