# Generated by Django 2.0.3 on 2018-03-17 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_name'], name='idx__orders__customer_name'),
        ),
    ]
